### ISSUE TITLE
WhereHas in criteria

### ISSUE THREAD

**Issue by mech-tools** [AaronJan/Housekeeper#1]
Hello,

I am trying your package. Seems great !

How would you add a whereHas constraint to the query ? (could be withTrashed())
I tried to create a criteria, but the model property is protected and therefore inaccessible.

E.g :

``` php
/**
     * The constructor
     * @param string $relation
     * @param string $attribute
     * @param string $value
     * @param string $operator
     */
    public function __construct($relation, $attribute, $value, $operator = '=')
    {
        $this->relation = $relation;
        $this->attribute = $attribute;
        $this->value = $value;
        $this->operator = $operator;
    }

    /**
     * Apply the criteria
     * @param  RepositoryInterface $repository
     */
    public function apply(RepositoryInterface $repository)
    {
        // Determine whether 'and' or 'or'
        $method = is_null($this->or) ? 'whereHas' : 'orWhereHas';

        // Get the the attributes as an array
        $relations = explode('.', $this->relation);

        // Create closure for the whereHas method
        $closure = function($q) use(&$closure, &$relations)
        {
            if (count($relations) > 0)
            {
                $q->whereHas(array_shift($relations), $closure);
            }
            else
            {
                $q->where($this->attribute, $this->operator, $this->value);
            }
        };

        // Apply the criteria to the model
        $repository->model->{$method}(array_shift($relations), $closure);
    }
```

EDIT : I need a criteria since i want to be able to call paginate() after applying this criteria. Looking at your code, I can't see how I can do this with findWhere() or findByFields() (they both call get()).

Thanks.

**Comment by mech-tools** [comment]
Ok, so I made it work, but now I have problems with cache since the whereHas() method use a closure : 

"Serialization of 'Closure' is not allowed"

``` php
/**
     * The constructor
     * @param string $relation
     * @param string $attribute
     * @param string $value
     * @param string $operator
     */
    public function __construct($relation, $attribute, $value, $operator = '=')
    {
        $this->relation = $relation;
        $this->attribute = $attribute;
        $this->value = $value;
        $this->operator = $operator;
    }

    /**
     * Apply the criteria
     * @param  RepositoryInterface $repository
     */
    public function apply(RepositoryInterface $repository)
    {
        // Get the the attributes as an array
        $relations = explode('.', $this->relation);

        // Create closure for the whereHas method
        $closure = function($q) use(&$closure, &$relations)
        {
            if (count($relations) > 0)
            {
                $q->whereHas(array_shift($relations), $closure);
            }
            else
            {
                $q->where($this->attribute, $this->operator, $this->value);
            }
        };

        // Apply the criteria to the model
        $repository->applyWhere([$closure], $this->or);
    }
```

**Comment by mech-tools** [comment]
Ok, we can use a closure if we also use the SuperClosure package (already used by Laravel) : 

``` php
/**
     * @param  array      $where
     * @param  bool|false $or
     * @return $this
     */
    public function applyWhere(array $where, $or = false)
    {
        /**
         * Determine using "where" or "orWhere".
         */
        $whereFunction = $or ? 'orWhere' : 'where';

        /**
         * Transform closures in \SuperClosure\SerializableClosure.
         */
        $where = array_map(function($value){
            if($value instanceof \Closure) {
                return new \SuperClosure\SerializableClosure($value);
            }
            return $value;
        }, $where);

        /**
         * Save to conditons.
         */
        $this->addCondition($whereFunction, $where);

        foreach ($where as $field => $value) {
            if($value instanceof \SuperClosure\SerializableClosure) {
                /**
                 * Use Closure for complex query search.
                 */
                $this->model = $this->model->$whereFunction($value->getClosure());
            } elseif (is_array($value) && count($value) == 3) {
                /**
                 * If $value has 3 variables, then just ignore the $field, use
                 * what's in the $value instead.
                 */
                list($field, $condition, $val) = $value;
                $this->model = $this->model->$whereFunction($field, $condition, $val);
            } else {
                /**
                 * Simple equality compare.
                 */
                $this->model = $this->model->$whereFunction($field, '=', $value);
            }
        }

        return $this;
    }
```

With this, we can pass a closure to the findWhere() method without breaking the cache system.

The array_map thing is to convert every closures to a SerializableClosure object so that the user doesn't have to create the object himself. This makes sense since we always need to create a SerializableClosure object with a Closure (so the cache system does not break).

Should I make a PR ?

**Comment by AaronJan** [comment]
Hi ! Sorry for my late reply, I have been very busy these days.

Thanks for your suggestion! Caching with closure condition is one thing that I missed.

Even I have read all your posts, please allow me to rethink about `Cacheable` and test something.

BTW, your `WhereHas` `Criteria` is very cool.   : )

**Comment by AaronJan** [comment]
I think `Cacheable` only needs the uniqueness of every conditions, `SuperClosure` is a good solution( a little heavy for this ), but can we make it even more simple?

**Comment by mech-tools** [comment]
What makes a criteria unique is :
- The criteria itself (its feature. Why it was created)
- The parameters passed to the criteria

Serialize the criteria allows you to get all theses informations.

You could also get the class name (WhereHAsCriteria, OrWhereHasCriteria, WithTrashed ...) to get the reason (the why). And then get the parameters (maybe using get_object_vars or ReflectionClass).

Not sure it is a better idea ....

**Comment by AaronJan** [comment]
I fixed this bug:

https://github.com/AaronJan/Housekeeper/commit/6fca1a54aaea1de60ead06e282774a79f1fb4f7f

I think we don't need to use `SuperClosure` because we won't be doing `unserialize`. And after running some benchmarks, this is much faster, and I think the result is very unique.

Thank you again!

**Comment by mech-tools** [comment]
I'm not very familiar with ReflectionFunction but I don't think it will work properly.

``` php
public function action ($id, $userId)
{
    $this->repository->rememberCriteria(new \Namespace\WhereHasCriteria('users', 'id', $userId));
    $user = $this->repository->find($id);

    return $user;
}
```

In this example, the $userId passed to the WhereHasCriteria is different depending on the route.
So whether it is $userId 23 or id 72 or something else :
- The namespaces will be the same
- The number of parameters will be the same
- The start line will be the same
- The end line will be the same

The first time the user hits the action, it will store a cache key that matches all queries with the WhereHasCriteria and any value.

To be brief, you need the parameters's values to distinguish two queries with the same criteria but different values.

**Comment by AaronJan** [comment]
You're right.. please make a PR to fix this, thanks! :smile:

**Comment by AaronJan** [comment]
After I read your example again, I think it would works just fine, you can see the `getCacheId` method [here](https://github.com/AaronJan/Housekeeper/blob/6fca1a54aaea1de60ead06e282774a79f1fb4f7f/src/Housekeeper/Injections/Cacheable/AbstractCacheManager.php#L105).

`Housekeeper` used the parameters that pass to the `find` method in cache key calculation, so the keys are not the same, and the hash result for `Closure` in condition (like your example) should be the same.

**Comment by mech-tools** [comment]
Sorry, It was a bad example : 

``` php
public function action ($userId)
{
    $this->repository->rememberCriteria(new \Namespace\WhereHasCriteria('users', 'id', $userId));
    $records = $this->repository->all();

    return $records;
}
```

No parameters passed to the find method, same problem.

**Comment by AaronJan** [comment]
https://github.com/AaronJan/Housekeeper/commit/fbf2adbc8bde9510b3f3b45a870b9791f4b4cfda

Fixed that, have a try!

**Comment by mech-tools** [comment]
Well done !

A made a test on my own :

``` php
namespace Test;

// The criteria itself
class TestCriteria
{
    protected $property;
    protected $value;

    public function __construct($property, $value)
    {
        $this->property = $property;
        $this->value = $value;
    }

    public function handle()
    {
        $property = $this->property;
        $value = $this->value;
        $parameter = 'another parameter';

        $closure = function($parameter) use($property, $value)
        {
            return $property . $value . $parameter;
        };

        return $closure;
    }
}

// Instantiate the criteria
$Criteria = new TestCriteria('users', 42);

// Get the closure
$closure = $Criteria->handle();

// Reflection and results
$reflection = new \ReflectionFunction($closure);

$result = [
    'obj' => $reflection->getClosureThis(),
    'getNumberOfParameters' => $reflection->getNumberOfParameters(),
    'getNamespaceName' => $reflection->getNamespaceName(),
    'getStartLine' => $reflection->getStartLine(),
    'getEndLine' => $reflection->getEndLine(),
];

var_dump($result);

/*
array (size=5)
  'obj' => 
    object(Test\TestCriteria)[2]
      protected 'property' => string 'users' (length=5)
      protected 'value' => int 42
  'getNumberOfParameters' => int 1
  'getNamespaceName' => string 'Test' (length=4)
  'getStartLine' => int 23
  'getEndLine' => int 26
*/
```

Not sure you really need :
- getNumberOfParameters
- getNamespaceName (you already have the namespace with getClosureThis())
- getStartLine (getClosureThis() seems enough, don't you think ?)
- getEndLine (getClosureThis() seems enough, don't you think ?)

As for getNumberOfParameters(), it is really usefull if you can get the parameters's value of the closure. (I didn't find any way to do that).

The only case where this will not work is if the user pass a parameter to the closure depending on the criteria parameters, like so :

``` php
public function handle()
    {
        $property = $this->property;
        $value = $this->value;
        // The user build a variable passed to the closure depending on the class parameters
        $parameter = $property === 'test' ? 'parameter test' : 'another parameter';

        $closure = function($parameter) use($property, $value)
        {
            return $property . $value . $parameter;
        };

        return $closure;
    }
```

But a user should not write a criteria this way. He should write two criteria  to preserve the uniqueness and the readability. So I don't think this is an issue you should tackle/solve. :)
