### ISSUE TITLE
Question about Before and After Flow

### ISSUE THREAD

**Issue by mech-tools** [AaronJan/Housekeeper#2]
Hello,

I am wondering why the Before and After injections are executed before and after the required method (e.g update(...)) and not within the method ?

To be clear, with the way the flow works, you can't modify the model itself right ? Or did I miss something ?

Example :

Assuming I want to create a new record with a relation.

``` php
public function create(array $attributes)
    {
        return $this->wrap(function ($attributes) {

            /////// -- The instance is created after the BEFORE injections -- ///////
            /////// -- We can not modify the model instance before save then ? -- ///////
            $model = $this->model->newInstance($attributes); 
            /**
             * @var Model $model
             */
            $model->save();

            return $model;

        }, new Action(__METHOD__, func_get_args(), Action::CREATE));
    }
```

So if I want to pass the relation as an argument, I can't create a BEFORE flow that automatically associates the relation to the model.

Of course, I could do it after the call to the repository in my controller / command  (or whatever) but : 
- It won't respect the DRY principle.
- This is not the responsibility of the controller / command to create the associations (this is the repository responsibility)
- The model would be saved twice (in the repository first, then in the controller / command after the association)

Same issue about the modification of the arguments ? Ex : modify an argument before saving the model.

Thanks,

**Comment by AaronJan** [comment]
Could you been more specific with some examples? I couldn't get what you trying to achieve.

**Comment by mech-tools** [comment]
Hello,

Here is an example.

I want to transform that :

``` php
// Create the model
$userModel = $userRepository->create([
    'first_name' => 'Dark',
    'last_name' => 'Dindon'
]);

// If something wrong
if(! $userModel)
{
    throw new \Exception('Oups, something wrong during the creation !');
}

// Associate a role
$userModel->role()->associate('role_id');
$userModel->save();
```

in : 

``` php
// Create the model
$userModel = $userRepository->create([
    'first_name' => 'Dark',
    'last_name' => 'Dindon',
    'role' => 'role_id'
]);

// If something wrong
if(! $userModel)
{
    throw new \Exception('Oups, something wrong during the creation !');
}
```

But to do this, I need to be able to access the $model->role property, just before the record is created.

With the current code, I don't see how this is possible. There is no hooks available after the model is instantiated but before the record is created.

``` php
public function create(array $attributes)
{
    return $this->wrap(function ($attributes) {

        $model = $this->model->newInstance($attributes); 

        /** -------   NO HOOK HERE   -------- */

        /**
         * @var Model $model
         */
        $model->save();

        return $model;

    }, new Action(__METHOD__, func_get_args(), Action::CREATE));
}
```

Another example would be :

``` php
// Get the inputs
$inputs = [
    'first_name' => 'Dark',
    'last_name' => 'Dindon'
];

// Define a new attribute
$fullWeirdName = $inputs['first_name'] . $inputs['last_name'] . '- WEIRDDDDD'; // DarkDindon-WEIRDDDDD

// Create the model with the new attribute
$userModel = $userRepository->create(array_add(
    $inputs,
    'weird_name',
    $fullWeirdName
));

// If something wrong
if(! $userModel)
{
    throw new \Exception('Oups, something wrong during the creation !');
}
```

I would like to move the creation logic of the attribute $model->weird_name inside the repository.

**Comment by AaronJan** [comment]
Let developer access `model` could cause some unexpected things ( I don't want to do that from the beginning ), like break the cache calculation.

I think this creation logic could be put in a new method, do you think so?

I will looking into this use case and talk back to you.

**Comment by mech-tools** [comment]
"I think this creation logic could be put in a new method, do you think so?" : I'am not sure I understand this.

What I mean is this issue is that it will be better if we can put the logic of after and before create/update/delete inside the repository so we don't have to repeat.

This is tedious and not dry :

``` php
public function createUser ()
{
    $userModel = $userRepository->create([
        'first_name' => 'Dark',
        'last_name' => 'Dindon'
    ]);

    // If something wrong
    if(! $userModel)
    {
        throw new \Exception('Oups, something wrong during the creation !');
    }

    // Associate a role
    $userModel->role()->associate('user_role_id');
    $userModel->save();
}

public function createAdmin ()
{
    $userModel = $userRepository->create([
        'first_name' => 'Dark',
        'last_name' => 'Dindon'
    ]);

    // If something wrong
    if(! $userModel)
    {
        throw new \Exception('Oups, something wrong during the creation !');
    }

    // Associate a role
    $userModel->role()->associate('admin_role_id');
    $userModel->save();
}
```

This is better but the model is still saved twiced (once for creation and once for association). And the application could have many jobs that create a user anyway :

``` php
public function createUser ()
{
    $this->dispatch(new \Namespace\CreateUserJob([
        'first_name' => 'Dark',
        'last_name' => 'Dindon',
        'role' => 'user_role_id'
    ]));
}

public function createAdmin ()
{
    $this->dispatch(new \Namespace\CreateUserJob([
        'first_name' => 'Dark',
        'last_name' => 'Dindon',
        'role' => 'admin_role_id'
    ]));
}

// JOB
public function handle()
{
    // Model is save here
    $userModel = $userRepository->create($this->attributes);

    // If something wrong
    if(! $userModel)
    {
        throw new \Exception('Oups, something wrong during the creation !');
    }

    // Associate a role
    // Model is save here again
    $userModel->role()->associate($this->attributes['role']);
    $userModel->save();

    return $userModel;
}
```

This is even better. The model is not saved twice and all the logic is centralised in the repository :

``` php
public function createUser ()
{
    $this->dispatch(new \Namespace\CreateUserJob([
        'first_name' => 'Dark',
        'last_name' => 'Dindon',
        'role' => 'user_role_id'
    ]));
}

public function createAdmin ()
{
    $this->dispatch(new \Namespace\CreateUserJob([
        'first_name' => 'Dark',
        'last_name' => 'Dindon',
        'role' => 'admin_role_id'
    ]));
}

// Job
public function handle()
{
    // Model is save here
    $userModel = $userRepository->create($this->attributes);

    // If something wrong
    if(! $userModel)
    {
        throw new \Exception('Oups, something wrong during the creation !');
    }

    return $userModel;
}

// Repository
class UserRepository extends BaseRepository {

    use Adjustable, Cacheable;

    protected function model()
    {
        return \Namespace\Models\User::class;
    }

    // This method is called by the repository if if exists
    protected function beforeCreate($model, $attributes)
    {
        $model->role()->associate($attributes['role'])
    }

}
```

The available methods could be (in this order) :
- before create / update / delete
- before save (update or create)
- after save (update or create)
- after create / update / delete

and this could be achieved this way : 

``` php
public function create(array $attributes)
{
    return $this->wrap(function ($attributes)
    {

        $model = $this->model->newInstance($attributes); 

        /** -------   HOOK HERE   -------- */
        $method = 'beforeCreate';
        if (method_exists($this, $method))
        {
            $result = call_user_func_array([$this, $method], [$model, $attributes]);
            if ($result === false) return $result;
        }

        /**
         * @var Model $model
         */
        $model->save();

        return $model;

    }, new Action(__METHOD__, func_get_args(), Action::CREATE));
}
```

This is just an example and this does not respect the flow you have implemented. So maybe there is a better solution for this package.

**Comment by AaronJan** [comment]
I think somethings you just have to repeat yourself a little bit ( because it's more clear to read and easy to maintain ), I may override the `create` method and put the `associate` logic in there, because most associations of repositories would be different from each other.

I'll leave logic like this to the user.  :smiley:

**Comment by mech-tools** [comment]
Ok. Maybe you are right.

For the record, the solution is allowing the user to define (or not) the before/after methods for each repository class. And therefor not override the base repository class.

If you already are overriding the repository methods, this is just a cleaner way to do it (without overriding).

**Comment by AaronJan** [comment]
Yes, `AOP` thing is great for some occasions, but `PHP` isn't cut out for this, hmm.. IMHO, it works good, but don't looks good.

**Comment by mech-tools** [comment]
Ok, if you think so.

This really doesn't need AOP. Just a simple "If the method exists then execute it before/after the rest of the code".
Laravel use it in many ways. One example is the "before/after filters".

IHMO, this looks better than overriding the complete method in the repository. For example, if you update the package, it won't break the code because you added a feature that is not in the overrided method.

**Comment by AaronJan** [comment]
I'm not trying to start an argument or something, just my personal preferences. :smiley: 

I don't want a lot of redundant codes, because there are many methods in repository, if I wrote codes like this, than user basically have to write their custom method like this, or have to remember what method is hookable.

I won't make any breaking changes in 0.9.x or 1.x, that's for 2.x ( I don't have any new idea yet ).

I'd love to talk about code, and I want to make sure people doesn't get me wrong. :smiley:
