### ISSUE TITLE
WithTrashed Criteria

### ISSUE THREAD

**Issue by mech-tools** [AaronJan/Housekeeper#3]
Hello,

Found another issue.
Assuming you have a model that can be softDelete with the SoftDeletes trait.

Every queries built with eloquent will have the following statement : `where `model`.`deleted_at` is null`

Now, if we want to get the trashed, we obviously need a criteria (so we don't have to extend the BaseRepository class and change everything around).

But a criteria only allows us to change the query with the "query builder" (not eloquent). And the withTrashed() method is not available for the query builder.

``` php
public function apply(RepositoryInterface $repository)
    {
        // Create the closure
        $closure = function($q)
        {
            // Won't work because $q-> gives us the query builder not eloquent
            $q->withTrashed();
        };

        // Apply the criteria to the model
        $repository->applyWhere([$closure]);
    }
```

You either need to implement the softDeletes feature or gives us access to the model instance in a criteria.
By only allowing us to access the query builder we are not able to perform several actions coupled to eloquent (like softDeletes).

Thanks,

**Comment by AaronJan** [comment]
I will implement `softDelete` in `BaseRepository`, thanks!   :+1:

**Comment by mech-tools** [comment]
:+1:

**Comment by AaronJan** [comment]
Added two methods: [`startWithTrashed`](https://github.com/AaronJan/Housekeeper/blob/master/src/Housekeeper/Eloquent/BaseRepository.php#L573) and [`startWithTrashedOnly`](https://github.com/AaronJan/Housekeeper/blob/master/src/Housekeeper/Eloquent/BaseRepository.php#L592).
